name: CI

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
      - run: composer global require laravel/pint
      - run: pint --test
